---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# yyyymm

<!-- badges: start -->
<!-- badges: end -->

The goal of yyyymm is to ...

## Installation

You can install the released version of yyyymm from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("yyyymm")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jbkunst/yyyymm")
```
## Examples

This is a basic example which shows you how to solve a common problem:


### `ym_to_date`
```{r}
library(yyyymm)
ym_to_date(ym = c(200902, 201912), day = 1)
```

### `ym_diff`

```{r}
ym_diff(ym = c(200902, 201912), ym2 = c(200901, 201712))
```

### `ym_add_months`

```{r}
ym_add_months(c(200902, 201912), months = c(1, -12))
```

### `ym_format`

```{r}
ym_format(c(200902, 201912), "%B del %Y")
```

### `ym_div`

```{r}
year <- format(lubridate::ymd(20170101) + months(0:11), "%Y%m")
year

ym_div(year, ng = 3)

ym_div(year, ng = 4)
```

### `ym_seq`

```{r}
ym_seq(201303, 201512)
```

